/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package List;

import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.util.List;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;


/**
 *
 * @author MaySM
 */
public class TestList extends javax.swing.JFrame {
    List<Object> List = new ArrayList<>();

    /**
     * Creates new form TestList
     */
    public TestList() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTambah = new javax.swing.JButton();
        BtnTampil = new javax.swing.JButton();
        BtnHapus = new javax.swing.JButton();
        BtnUbah = new javax.swing.JButton();
        BtnKosongkan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        MessageArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnTambah.setText("Tambahkan Objek");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        BtnTampil.setText("Tampilkan Isi List");
        BtnTampil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTampilActionPerformed(evt);
            }
        });

        BtnHapus.setText("Hapus Objek");
        BtnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHapusActionPerformed(evt);
            }
        });

        BtnUbah.setText("Ubah Objek");
        BtnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUbahActionPerformed(evt);
            }
        });

        BtnKosongkan.setText("Kosongkan List");
        BtnKosongkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKosongkanActionPerformed(evt);
            }
        });

        MessageArea.setColumns(20);
        MessageArea.setRows(5);
        jScrollPane1.setViewportView(MessageArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnKosongkan)
                    .addComponent(BtnUbah)
                    .addComponent(BtnHapus)
                    .addComponent(BtnTampil)
                    .addComponent(btnTambah))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnTambah)
                        .addGap(18, 18, 18)
                        .addComponent(BtnTampil)
                        .addGap(18, 18, 18)
                        .addComponent(BtnHapus)
                        .addGap(18, 18, 18)
                        .addComponent(BtnUbah)
                        .addGap(18, 18, 18)
                        .addComponent(BtnKosongkan)
                        .addGap(0, 79, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here
        Object input = JOptionPane.showInputDialog(this, "Ketikkan apapun",
                "Tambah elemnt", JOptionPane.INFORMATION_MESSAGE);
        if(input == null || "".equals(input)){
            JOptionPane.showMessageDialog(this, "Anda belum mengetikan"
                + "elemen yang akan ditambahkan");
        }else{
            List.add(input);
           MessageArea.append("Menambahkan objek '"+input+"' ke dalam List\n");
        }
    }//GEN-LAST:event_btnTambahActionPerformed

    private void BtnTampilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTampilActionPerformed
        // TODO add your handling code here:
        if(List.size() > 0){
            MessageArea.setText("");
            List.forEach((object) -> {
                MessageArea.append("" + object + "\n");
            });
        }else{
            JOptionPane.showMessageDialog(this, "List Kosong");
        }
    }//GEN-LAST:event_BtnTampilActionPerformed

    private void BtnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHapusActionPerformed
        // TODO add your handling code here:
        JDialog dialog = new JDialog(this, "Hapus isi List",true);
        JPanel panel = new JPanel(new BorderLayout());
        JComboBox combo = new JComboBox();
        List.forEach((Object) -> {
            combo.addItem(Object);
    });
        JButton hapus = new JButton("Hapus");
        hapus.addActionListener((ActionEvent e) -> {
            if(List.size() > 0){
                Object obj = combo.getSelectedItem();
                List.remove(obj);
                combo.removeAllItems();
                List.forEach((Object) -> {
            });
                JOptionPane.showMessageDialog(TestList.this, "Berhasil"
                + " mnghapus element list");
            }else{
                JOptionPane.showMessageDialog(TestList.this, "Tidak ada elemen"
                + " dalam list");
            }
        });
        panel.add(combo, BorderLayout.CENTER);
        panel.add(hapus, BorderLayout.SOUTH);
        dialog.add(panel);
        dialog.setLocationRelativeTo(null);
        dialog.pack();
        dialog.setVisible(true);
    }//GEN-LAST:event_BtnHapusActionPerformed

    private void BtnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUbahActionPerformed
        // TODO add your handling code here:
        JDialog dialog = new JDialog(this, "Ubah isi List", true);
        JPanel panel = new JPanel (new BorderLayout());
        JComboBox combo = new JComboBox();
        List.forEach((object) -> {
            combo.addItem(object);
        });
        JTextField txtEdit = new JTextField();
        JButton hapus = new JButton("Ubah");
        hapus.addActionListener((ActionEvent e) -> {
            if(List.size() > 0) {
                Object newObject = txtEdit.getText();
                if(!txtEdit.getText().isEmpty()) {
                    Object obj = combo.getSelectedItem();
                    int index = combo.getSelectedIndex();
                    List.set(index, newObject);
                    combo.removeAllItems();
                    List.forEach((object) -> {
                        combo.addItem(object);
                });
                combo.setSelectedIndex(index);
                txtEdit.setText("");
                JOptionPane.showMessageDialog(TestList.this,"Berhasil"
                        + "mengubah elemen List");
                }else{
                JOptionPane.showMessageDialog(TestList.this, "Masukan"
                        + "elemen/objek");
                txtEdit.requestFocus();
                }
            }else{
                JOptionPane.showMessageDialog(TestList.this, "Tidak ada elemen"
                        + "dalam liat");
            }    
                
        });
        panel.add(combo, BorderLayout.NORTH);
        panel.add(txtEdit, BorderLayout.CENTER);
        panel.add(hapus, BorderLayout.SOUTH);
        dialog.add(panel);
        dialog.setLocation(null);
        dialog.pack();
        dialog.setVisible(true);
            

    }//GEN-LAST:event_BtnUbahActionPerformed

    private void BtnKosongkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKosongkanActionPerformed
        // TODO add your handling code her
        List.clear();
        JOptionPane.showMessageDialog(TestList.this,"semua elemen dalam list"
                + "telah di hapus");
    }//GEN-LAST:event_BtnKosongkanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnHapus;
    private javax.swing.JButton BtnKosongkan;
    private javax.swing.JButton BtnTampil;
    private javax.swing.JButton BtnUbah;
    private javax.swing.JTextArea MessageArea;
    private javax.swing.JButton btnTambah;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
